# Generated by Django 5.2.11 on 2026-02-16 10:27

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Department_Name', models.CharField(max_length=15)),
                ('Description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.getFileName)),
                ('status', models.BooleanField(default=False, help_text='0:Show, 1:Hidden')),
                ('specialist', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
